### PR TITLE
Adding tvOS support

### PR DESCRIPTION
**Pull request by bruceflowers**
Rebased against your master branch. Built all schemes of Runes from a dependent library (Argo) to test, and that was successful.

I recognize this will require developers to use Xcode 7.1, so just let me know if you've got different ideas about where this might want to go.

### CODE REVIEW

**Comment by gfontenot** [comment]
This is great. Unfortunately, sharing the scheme for this will break Carthage installs. Can you un-share that scheme, and then I can open a `tvos` branch and re-share it?

**Comment by bruceflowers** [comment]
No problem - updated and awaiting your review.

**Comment by bruceflowers** [comment]
Bump - @gfontenot is there anything I still need to do for this or is it pretty much good to go?  Hoping to be able to help get this use case worked out for Argo...

Also, if you can open that tvOS branch, I can get the reshared scheme up there so there's less for you to do...

**Comment by gfontenot** [comment]
Sorry about that! All set now. `tvos` branch has also been created, and the scheme is shared on that branch.

**Comment by bruceflowers** [comment]
Great!  Thanks @gfontenot

**Pull request merged**
