### PR TITLE
What about default implementations for SequenceType?

### PR DESCRIPTION
**Pull request by sharplet**
Notes regarding `<*>`: It doesn't seem possible to create a generic type constraint over a sequence of `A -> B`, so this version uses `[A -> B]` as a workaround (which is no problem when combined with `<^>`, which returns an `Array`). i.e., Swift borks at this:

```
func <*> <F: SequenceType, S: SequenceType, A, B where F.Generator.Element == A -> B, S.Generator.Element == A> (fs: F, source: S) -> [B] {
                                                                              ^^^^^^ NOPE
```

I didn't think too hard about style, naming, etc., that's all up for grabs! Just keen to know if you're into this idea.

### CODE REVIEW

**Comment by sharplet** [comment]
Hmm on second thought, it seems kind of weird to me that these implementations coerce everything into an `Array`. I'm thinking it might make more sense for this to just be specific to `Array`.

**Comment by gfontenot** [comment]
Yeah, I was going to say the same thing. I think this is awesome, and would love to pull it in, but lets change everything to just be for `Array`. If people create their own `SequenceType`... types, then they could also add their own implementations for these functions.

**Comment by gfontenot** [comment]
Also, style-wise, lets keep with the `T -> U` naming scheme for the generics so that it matches with the built in type signature.

**Comment by sharplet** [comment]
Ok, pushed some changes! Let me know what you think.

**Comment by gfontenot** [comment]
Fantastic, thank you for this. Squashed and merged in 0755117

**Comment by sharplet** [comment]
🎉✊

**Pull request closed without merging**
