### PR TITLE
Misc cleanup tasks

### PR DESCRIPTION
**Pull request by gfontenot**
Been wanting to do this for a while

### CODE REVIEW

**Comment by jshier** [comment]
The `.swift-version` file is still required by CocoaPods to properly lint your podspec.

**Comment by gfontenot** [comment]
well that's a bummer.

**Comment by ikesyo** [comment]
In CocoaPods 1.1.0 final, Swift 3.0 is used by default during validation. And also you can pass `--swift-version=VERSION` option.

https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0

**Comment by jshier** [comment]
Thanks, I'd forgotten they added those at release.

**Comment by gfontenot** [comment]
Splendid news

**Pull request merged**
