### PR TITLE
Swift 4/Xcode 9 support

### PR DESCRIPTION
**Pull request by gfontenot**
Includes support for `swift test`!

### CODE REVIEW

**Comment by sharplet** [comment]
Tested this out by consuming this branch from a test package, and observed the following:

- The test dependencies are _fetched_ by swiftpm
- They don't seem to be built
- I can depend on Runes' products, but if I try and depend on Mozart or SwiftCheck, I get this error:

    ```
    error: The product dependency 'SwiftCheck' was not found.
    ```

So that seems good enough 👍

**Comment by sharplet** [comment]
Is the plan to drop support for the swift 3 compiler on master?

**Comment by gfontenot** [comment]
> The test dependencies are fetched by swiftpm

Wild. I hadn't expected that. I guess as long as they aren't built, that's fine though.

> Is the plan to drop support for the swift 3 compiler on master?

I guess we don't have to? That's been our pattern, but since the Swift 4 compiler supports both it doesn't seem like we _need_ to do that anymore. Is that what the `swiftLanguageVersions` thing in Package.swift is for?

**Comment by sharplet** [comment]
So I think `swiftLanguageVersions` can give you forwards compatibility, for example documenting that you can compile under Swift 4. But I don't think you can get backwards compatibility: a Swift 4 package file won't compile back in Swift 3. So if we want to make use of Swift 4-specific features in our manifest, we can't also support the Swift 3 compiler.

**Comment by jshier** [comment]
You can use Swift version checks in the package file as well.

**Comment by sharplet** [comment]
True, though I'm not sure how that would interact with the `swift-tools-version`. If the tools version was 3, but we had a conditional section for Swift 4, would the latter ever be executed by the package manager?

**Comment by gfontenot** [comment]
This went stale. I'm going to re-open this as a focused PR to add support for `swift test` and the new package format where we can discuss compiler support directly.

**Pull request closed without merging**
